### ISSUE TITLE
after click to run DeNet-Storage, Nothing happened on MacOS

### ISSUE THREAD

**Issue by malian275** [DeNetPRO/StorageProvider#1]
I use MacOS, so I download DeNet-Storage-linux-amd64.zip, and then unzip, and then click DeNet-Storage file, and then it open terminal and then terminal closed, and then Nothing happened.
Did I do something wrong?

**Comment by djdeniro** [comment]
Hello! Version for MacOS will published soon!

**Comment by djdeniro** [comment]
Latest version [here](https://github.com/DeNetPRO/StorageProvider/releases)!
