### ISSUE TITLE
Can`t create account

### ISSUE THREAD

**Issue by Filin00** [DeNetPRO/StorageProvider#2]
Tryin to create new account from DeNet-Storage, but the only thing happening is loading... (see pic)
What should I do?
![2021-12-17_03-26-48](https://user-images.githubusercontent.com/96271000/146468636-e2870831-b992-4b52-9ce3-ee4c7288a0d6.png)

Если знаете русский, то можно отвечать на нём же)

**Comment by djdeniro** [comment]
Привет! 

Прошлой версией пользовался? 0.3.0?

**Comment by djdeniro** [comment]
Fixed in v1.0.0
